#!/bin/sh
set -e

# see https://github.com/docker-library/php/blob/master/8.1/alpine3.17/fpm/docker-php-entrypoint
# Add specific startup command
cp .env.example .env
composer install
php artisan key:generate
php artisan migrate:fresh --force --seed --isolated

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- php-fpm "$@"
fi

exec "$@"
