name: "Static Analysis"

on: [ push, pull_request ]

env:
  WORKING_DIR_API: "platform"
  PROJECT_NAME: 'actual'

jobs:
  analyse_api:
    strategy:
      fail-fast: false
      matrix:
        php: [ "8.3" ]
        laravel: [ "^11.0"]

    name: "P${{ matrix.php }} - L${{ matrix.laravel }}"

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: "actions/checkout@v4"

      - name: Setup PHP
        uses: "shivammathur/setup-php@v2"
        with:
          php-version: "${{ matrix.php }}"
          extensions: json, dom, curl, libxml, mbstring, zip, gd, intl, fileinfo
          tools: composer:v2
          coverage: xdebug

      - name: Set up Node & NPM
        uses: actions/setup-node@v2
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --ansi
        working-directory: ${{ env.WORKING_DIR_API }}

      - name: Validate composer
        run: composer validate --strict
        working-directory: ${{ env.WORKING_DIR_API }}

      - name: Install dependencies
        run: yarn install
        working-directory: ${{ env.WORKING_DIR_API }}

      - name: Build dependencies
        run: yarn run build
        working-directory: ${{ env.WORKING_DIR_API }}

      - name: Up Laravel Application
        run: |
          cd ${{ env.WORKING_DIR_API }}/
          cp .env.example .env 
          php artisan key:generate

      - name: Tests
        run: composer test

